### ISSUE TITLE
Create a new repository for Conjur base docker images

### ISSUE THREAD

**Issue by sashaCher** [cyberark/conjur-template#11]
## Request for a new public Conjur project in CyberArk GitHub

**Current project source:** It's new project

**Current maintainer:** Sasha Chernomordik, @sashaCher 

**Desired project URL:** https://github.com/cyberark/conjur-base-image

**Brief description of project:**
As a part of the making Conjur FIPS complaint effort we are building new base images those will be FIPS compliant.

Those images will replace `ubuntu:18.04` and `phusion/baseimage:0.11` base images in conjur repository.

**Anticipated [certification level](https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md):** Trusted

**Comment by izgeri** [comment]
@sashaCher I've created an empty project from this template repo here: https://github.com/cyberark/conjur-base-image

On your first pull request you will see a checklist in the PR description - you can use this to guide you on the steps needed to make the repo public. Please tag me as a reviewer once the project is ready for review, and I can review and make it public. 

It's ok with me if we make it public first and then continue to work on the automatic image publishing - I'll leave the exact timeline up to you. Please let me know if you run into any issues!
