### ISSUE TITLE
Conjur Teamcity Plugin

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/conjur-template#17]
## Request for a new public Conjur project in CyberArk GitHub

Current project source: https://github.com/eemotacyber/Teamcity

Current maintainer: Andrew Copeland, AndrewCopeland

Desired project URL: https://github.com/cyberark/conjur-teamcity-plugin

Brief description of project:
Allows the ability to retrieve credentials from conjur when a Teamcity job/build is kicked off. This is a plugin that can be imported into the Teamcity Server.

Anticipated [certification level](https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md): Community (For now but l would like to get it to trusted at some point)

**Comment by izgeri** [comment]
Hey @AndrewCopeland - I've created https://github.com/cyberark/conjur-teamcity-plugin for you.

On your first pull request you will see a checklist in the PR description - you can use this to guide you on the steps needed to make the repo public. Please tag me as a reviewer once the project is ready for review, and I can review and make it public.

**Comment by AndrewCopeland** [comment]
The repo has been made and has been moved to public. Thanks!!!!
