### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-template#2]
We often use this repo to create new projects. It can help that process be more efficient if we had a PR template that has:
- A top section with a checklist of what needs to be done to prepare the code to be migrated, including filling in the TODOs in this template repo and (if going public) the items in the [public repo guidelines](https://github.com/cyberark/employee-guidelines/blob/master/guidelines/public_repos_checklist.md)
- A checklist item for removing the top section in the first PR
- The regular PR template at the bottom, which can be taken from [Conjur](https://github.com/cyberark/conjur/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by JakeQuilty** [comment]
PR: https://github.com/cyberark/conjur-template/pull/4
